version: '3.8'
services:
  web_api:
    image: maialenigar/web_api:v2
    build: .
    ports:
      - 7007-7015:7007 # We set a range of ports so that when scaling, we can use them
    env_file:
      - .env
    depends_on:
      - mongodb
    networks:
      - my-network
    deploy:
      resources:
        limits:
          cpus: '0.5'  # Limit CPU usage to 50%
          memory: 256M # Limit memory usage to 256 megabytes

  mongodb:
    image: mongo:4.0.7
    container_name: mongodb-container
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongodb_root_password
      MONGO_INITDB_DATABASE: testdb
    volumes:
      - mongodb-volume:/data/db
    ports:
      - 27017:27017
    networks:
      - my-network
    deploy:
      resources:
        limits:
          cpus: '0.5'  # Limit CPU usage to 50%
          memory: 512M # Limit memory usage to 512 megabytes
    secrets:
      - mongodb_root_password
  
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD_FILE: /run/secrets/mongodb_root_password
      ME_CONFIG_MONGODB_SERVER: mongodb # use the name of the mongo container
    ports:
      - 8081:8081
    depends_on:
      - mongodb
    networks:
      - my-network
    secrets:
      - mongodb_root_password

secrets:
  mongodb_root_password:
    file: ./mongo-pass.txt

volumes:
  mongodb-volume:

networks:
  my-network:
    driver: bridge