apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-data-pv
  namespace: maialen-namespace
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1024Mi
  hostPath:
    path: /data/mongo-data-pv
    type: "" # default to a generic volume type
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  volumeMode: Filesystem