apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-api
  template:
    metadata:
      labels:
        app: web-api
    spec:
      containers:
      - name: web-api
        image: maialenigar/web_api:v1
        ports:
        - containerPort: 7007
        env:
        - name: Entorno
          value: "maialenigar"
        - name: Mongodb
          value: "mongodb://root:password@10.103.113.184:27017"
---
apiVersion: v1
kind: Service
metadata:
  name: web-api-service
spec:
  selector:
    app: web-api
  ports:
  - protocol: TCP
    port: 7007
    targetPort: 7007
