apiVersion: v1
kind: Pod
metadata:
  name: web-api-pod
  labels:
    app: web-api
spec:
  containers:
  - name: web-api
    image: maialenigar/web_api:v1
    ports:
    - containerPort: 7007
    env:
    - name: Entorno
      value: "maialenigar"
    - name: Mongodb
      value: "mongodb://root:password@10.102.141.79:27017"
---
apiVersion: v1
kind: Service
metadata:
  name: web-api-service
spec:
  selector:
    app: web-api
  ports:
  - protocol: TCP
    port: 7007
    targetPort: 7007
