apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
  namespace: maialen-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
      - name: mongo-express
        image: mongo-express:latest
        ports:
        - containerPort: 8081
          protocol: TCP
        env:
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          value: root
        - name: ME_CONFIG_MONGODB_SERVER
          value: mongodb
        envFrom:
        - secretRef:
            name: mongo-express-secret
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-express
  namespace: maialenigar-namespace
spec:
  selector:
    app: mongo-express
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
